### ISSUE TITLE
No VPC Support

### ISSUE THREAD

**Issue by arthurdead** [WootsMX/InSource#1]
vpc support would be great this fork https://github.com/NicolasDe/AlienSwarm has vpc support

i made these for my personal use:
https://dl.dropboxusercontent.com/u/56245217/client_insource.vpc
https://dl.dropboxusercontent.com/u/56245217/server_insource.vpc

**Comment by Kolesias17** [comment]
Thank you very much! I was looking for exactly this. I will review it and include it in the repository.
