### ISSUE TITLE
[SUGGESTION] Make The Bots Help ThePlayer if they are climbing or dejected

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [WootsMX/insource#13]
title

**Comment by kolessios** [comment]
Fixed:
https://github.com/WootsMX/insource/commit/42818d5a469d6a58062b15b623b64b957804232b

Notes:
- I have added the function "[ShouldKnownDejectedFriends()](https://github.com/WootsMX/insource/blob/42818d5a469d6a58062b15b623b64b957804232b/game/server/in/bots/components/bot_component_decision.cpp#L569)" in "CBotDecision" to establish if the Bots can know if a friend is dejected, even if they are not seeing it.
