### ISSUE TITLE
Left 4 Dead 2 Models Don´t Work Whit InSource

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [WootsMX/insource#2]
I Create a folder inside of "modules" named l4d2 and put the entire content of left 4 dead 2 but they dont work the playermdodels is not showing up

**Comment by kolessios** [comment]
Unfortunately it does not work just by putting the files in the "modules" folder, you have to add those folders in the GameInfo:

https://github.com/WootsMX/insource-games/blob/master/apocalypse/GameInfo.txt

In addition, you may experience problems using the original L4D2 models (mainly models for players), I had to recompile them to Alien Swarm using:

http://steamcommunity.com/groups/CrowbarTool

**Comment by FriskTheFallenHuman** [comment]
its just the player models whit the anims or just the player models? because the anims don't compile also is need you have the entire left 4 dead 2 content or just the materials, models, weapons, npc ??

EDIT: sorry for my bad english

**Comment by FriskTheFallenHuman** [comment]
also you can redistribute a modified version of the models ( just only that use Insource to work ) EX: the modified Playermodels, weapons  and NPC

**Comment by kolessios** [comment]
I will try to update the repository [insource-games](https://github.com/WootsMX/insource-games) with the models needed to run InSource. The reason I have not done it is because of my connection, but I will try. I also need to update this repository with changes I forget to upload.

However, it is not absolutely mandatory to use L4D2 content but of course you would have to modify the Player file/NPC's files to use the models you want.

For weapons, the model is declared in its own .txt file in the /scripts/ folder of the game files.

And I think for now is the only thing you have to modify, the textures and other models are just to decorate the maps, but you can create your own maps.

**Comment by kolessios** [comment]
I have already updated InSource and insource-games but I will not be able to upload the Player/Weapon models until a few hours later. (They are very heavy)

However I can help you a little if you want to use the L4D2 models. As I said you need the models of players (survivors), weapons and optionally the infected if you want to create one.

You can see the models you need here:

https://github.com/WootsMX/insource/blob/master/game/server/ap/ap_player.cpp#L24
https://github.com/WootsMX/insource/blob/master/game/server/in/npc_infected.cpp#L83

You do not need to recompile the animations, just the models and as you can see also the models of the hands.

I have placed those files in the folders:

/content/mod/players/
/content/mod/infected/
/content/mod/weapons/

But if you do not want to complicate your life by ordering everything like me, you can do it directly in the root:

/models/infected/
/models/survivors/ (need to be recompiled)
/models/weapons/arms/ (need to be recompiled)
/models/v_models/ (some need recompiled)
/models/w_models/

/materials/models/

If you need more help setting everything up for InSource, let me know.

**Comment by FriskTheFallenHuman** [comment]
oh tanks and sorry for being annoying but, regarding the materials that are needed ??

**Comment by kolessios** [comment]
I think it would only be enough to copy all the materials in the folder:

/materials/models/

You can also try to just copy the whole folder of _materials_, but personally doing this I had problems (crash) in Hammer Editor.

**Comment by FriskTheFallenHuman** [comment]
well in someone PC crash in other its just buggy
i think that the content used for SFM will work
