### ISSUE TITLE
[BUG] The Swing animation dont work 

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [WootsMX/insource#4]
when the player is on water the player is on T pose.
this seems to be a bug whit the player animation system

**Comment by kolessios** [comment]
I have not done underwater experiments, and in addition the L4D2 models do not have animation to swim, however you can make them use walking/running/etc animations in this file:

https://github.com/WootsMX/insource/blob/master/game/shared/ap/ap_player_shared.cpp

I'll also try to solve that in a few minutes.

**Comment by FriskTheFallenHuman** [comment]
that bug seem to be a left over from Source 2007 and still present in Source SDK 2013 only in Counter strike is fixed

**Comment by kolessios** [comment]
It is not that difficult to solve, the Base Animation System already detects when the player is under water, but it is necessary to translate that animation to an animation that uses the models of your game.

**Comment by kolessios** [comment]
Fixed: https://github.com/WootsMX/insource/commit/37de656ec2b2e14f7851aa812d0067c47b6f76a4
